(()=>{
const grades=[['A+',4],['A',3.75],['A-',3.5],['B+',3.25],['B',3],['B-',2.75],['C+',2.5],['C',2.25],['C-',2],['D+',1.75],['D',1.5],['E',0]];
const degrees={bachelor:{label:'بكالوريوس',minGrade:1.5,minAverage:2},diploma:{label:'دبلوم',minGrade:2.25,minAverage:2.5},master:{label:'ماجستير',minGrade:2.5,minAverage:3},phd:{label:'دكتوراة',minGrade:2.5,minAverage:3}};
const list=document.getElementById('courseList'),previousGpa=document.getElementById('previousGpa'),previousHours=document.getElementById('previousHours'),semesterOut=document.getElementById('semesterGpa'),cumulativeOut=document.getElementById('cumulativeGpa'),statusOut=document.getElementById('gpaStatus'),detailsOut=document.getElementById('gpaDetails');let degree='bachelor',courseId=0;
const gradeOptions=grades.map(([g])=>`<option value="${g}">${g}</option>`).join('');
function addCourse(saved={}){courseId++;const row=document.createElement('article');row.className='course-row';row.dataset.id=courseId;row.innerHTML=`<label><span class="field-label">اسم المادة</span><input class="site-input course-name" placeholder="مثال: رياضيات 1" value="${saved.name||''}"></label><label><span class="field-label">العلامة</span><select class="site-select course-grade">${gradeOptions}</select></label><label><span class="field-label">الساعات</span><select class="site-select course-hours">${[1,2,3,4,5,6].map(h=>`<option value="${h}">${h}</option>`).join('')}</select></label><label class="course-repeat"><input type="checkbox" class="repeat-check"><span>مادة معادة</span></label><label class="old-grade-wrap"><span class="field-label">العلامة القديمة</span><select class="site-select old-grade">${gradeOptions}</select></label><button class="remove-course" type="button" aria-label="حذف المادة">×</button>`;row.querySelector('.course-grade').value=saved.grade||'A';row.querySelector('.course-hours').value=String(saved.hours||3);row.querySelector('.repeat-check').checked=!!saved.repeat;row.querySelector('.old-grade').value=saved.oldGrade||'E';row.classList.toggle('is-repeat',!!saved.repeat);row.querySelector('.repeat-check').onchange=e=>{row.classList.toggle('is-repeat',e.target.checked);calculate()};row.querySelector('.remove-course').onclick=()=>{row.remove();if(!list.children.length)addCourse();calculate()};row.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',calculate));list.appendChild(row)}
function classify(gpa){return gpa>=3.5?'ممتاز':gpa>=3?'جيد جداً':gpa>=2.5?'جيد':gpa>=2?'مقبول':'ضعيف'}
function readCourses(){return[...list.children].map(row=>({name:row.querySelector('.course-name').value.trim(),grade:row.querySelector('.course-grade').value,hours:Number(row.querySelector('.course-hours').value),repeat:row.querySelector('.repeat-check').checked,oldGrade:row.querySelector('.old-grade').value}))}
function calculate(){const prevGpa=Math.max(0,Math.min(4,Number(previousGpa.value)||0)),prevHours=Math.max(0,Number(previousHours.value)||0),courses=readCourses(),rules=degrees[degree];let semesterPoints=0,semesterHours=0,addedPoints=0,addedHours=0,repeated=0,failed=0;for(const c of courses){const points=grades.find(([g])=>g===c.grade)[1];semesterPoints+=points*c.hours;semesterHours+=c.hours;if(points<rules.minGrade)failed++;if(c.repeat){const old=grades.find(([g])=>g===c.oldGrade)[1];addedPoints+=(points-old)*c.hours;repeated++}else{addedPoints+=points*c.hours;addedHours+=c.hours}}const semester=semesterHours?semesterPoints/semesterHours:0,totalHours=prevHours+addedHours,cumulative=totalHours?(prevGpa*prevHours+addedPoints)/totalHours:semester;semesterOut.textContent=semester.toFixed(2);cumulativeOut.textContent=Math.max(0,Math.min(4,cumulative)).toFixed(2);statusOut.textContent=`${classify(cumulative)} • ${cumulative>=rules.minAverage?'ضمن الحد المطلوب':'أقل من الحد المطلوب'}`;statusOut.classList.toggle('warning',cumulative<rules.minAverage);detailsOut.textContent=`${semesterHours} ساعة هذا الفصل • ${repeated} مواد معادة • ${failed} مواد تحت حد النجاح (${rules.minGrade.toFixed(2)})`;save();return{semester,cumulative,totalHours}}
function save(){const state={degree,previousGpa:previousGpa.value,previousHours:previousHours.value,courses:readCourses()};localStorage.setItem('vortexa-gpa',JSON.stringify(state))}
function reset(){localStorage.removeItem('vortexa-gpa');degree='bachelor';previousGpa.value=previousHours.value=0;list.innerHTML='';document.querySelectorAll('.degree-tab').forEach(b=>b.classList.toggle('active',b.dataset.degree===degree));addCourse();addCourse();addCourse();calculate()}
document.querySelectorAll('.degree-tab').forEach(b=>b.onclick=()=>{degree=b.dataset.degree;document.querySelectorAll('.degree-tab').forEach(x=>x.classList.toggle('active',x===b));calculate()});document.getElementById('addCourse').onclick=()=>{addCourse();calculate()};document.getElementById('calculateGpa').onclick=calculate;document.getElementById('resetGpa').onclick=reset;previousGpa.addEventListener('input',calculate);previousHours.addEventListener('input',calculate);
try{const saved=JSON.parse(localStorage.getItem('vortexa-gpa'));if(saved){degree=degrees[saved.degree]?saved.degree:'bachelor';previousGpa.value=saved.previousGpa||0;previousHours.value=saved.previousHours||0;(saved.courses||[]).forEach(addCourse)}}catch{}if(!list.children.length){addCourse();addCourse();addCourse()}document.querySelectorAll('.degree-tab').forEach(b=>b.classList.toggle('active',b.dataset.degree===degree));calculate();
})();
