(()=>{
const data=window.CAMPUS_DATA;
const canvas=document.getElementById('campusCanvas');
const ctx=canvas.getContext('2d');
const stage=document.getElementById('mapStage');
const search=document.getElementById('mapSearch');
const results=document.getElementById('mapResults');
const details=document.getElementById('placeDetails');
const routeStart=document.getElementById('routeStart');
const routeEnd=document.getElementById('routeEnd');
const routeResult=document.getElementById('routeResult');
const colors={faculty:'#8D6BFF',medical:'#F06BD7',admin:'#FFD252',library:'#42D5C7',academic:'#CEC2FF',hall:'#FF9D5C',food:'#FFCF70',mosque:'#80D7A8',sportsC:'#69C6E7',pitch:'#A8DB8F',gate:'#17131F',service:'#A9A3B1',bank:'#FFD252',kiosk:'#FFCF70',landmark:'#6D4AFF',parking:'#C9C6CE',shelter:'#D7D3DF',carport:'#D7D3DF',unknown:'#C9C6CE'};
const labels={faculty:'الكليات',medical:'الطبي',admin:'الإدارة',library:'المكتبات',academic:'الأكاديمي',hall:'القاعات',food:'المطاعم',mosque:'المساجد',sportsC:'الرياضة',gate:'البوابات',service:'الخدمات'};
const hidden=new Set(['parking','shelter','carport','unknown']);
let flat=false,selected=null,hovered=null,dragging=false,moved=false,last={x:0,y:0};
const view={zoom:1,panX:0,panY:0};
let screenShapes=[],routePath=[],routeDistance=0;
const nodes=[];for(let i=0;i<data.nodes.length;i+=2)nodes.push({x:data.nodes[i],y:data.nodes[i+1]});
const graph=Array.from({length:nodes.length},()=>[]);for(let i=0;i<data.edges.length;i+=3){const a=data.edges[i],b=data.edges[i+1],w=data.edges[i+2];graph[a].push([b,w]);graph[b].push([a,w])}
const allPoints=[];
data.lines.forEach(line=>{for(let i=0;i<line.pts.length;i+=2)allPoints.push([line.pts[i],line.pts[i+1]])});
data.places.forEach(p=>(p.rings||[]).forEach(r=>{for(let i=0;i<r.length;i+=2)allPoints.push([r[i],r[i+1]])}));
const minX=Math.min(...allPoints.map(p=>p[0])),maxX=Math.max(...allPoints.map(p=>p[0])),minY=Math.min(...allPoints.map(p=>p[1])),maxY=Math.max(...allPoints.map(p=>p[1]));
const worldCenter={x:(minX+maxX)/2,y:(minY+maxY)/2};
function project(x,y){const angle=flat?0:-.66,c=Math.cos(angle),s=Math.sin(angle);return {x:x*c-y*s,y:(x*s+y*c)*(flat?1:.72)}}
const projected=allPoints.map(p=>project(p[0],p[1]));
const baseBounds={minX:Math.min(...projected.map(p=>p.x)),maxX:Math.max(...projected.map(p=>p.x)),minY:Math.min(...projected.map(p=>p.y)),maxY:Math.max(...projected.map(p=>p.y))};
function fitScale(){return Math.min((canvas.clientWidth-70)/(baseBounds.maxX-baseBounds.minX),(canvas.clientHeight-70)/(baseBounds.maxY-baseBounds.minY))}
function toScreen(x,y){const p=project(x,y),c=project(worldCenter.x,worldCenter.y),scale=fitScale()*view.zoom;return{x:canvas.clientWidth/2+(p.x-c.x)*scale+view.panX,y:canvas.clientHeight/2+(p.y-c.y)*scale+view.panY}}
function pathFromRing(r,raise=0){const path=new Path2D();for(let i=0;i<r.length;i+=2){const p=toScreen(r[i],r[i+1]);if(i===0)path.moveTo(p.x,p.y-raise);else path.lineTo(p.x,p.y-raise)}path.closePath();return path}
function shade(hex,amount){const n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+amount)),g=Math.max(0,Math.min(255,((n>>8)&255)+amount)),b=Math.max(0,Math.min(255,(n&255)+amount));return `rgb(${r},${g},${b})`}
function drawLocationIcon(x,y,color,size){ctx.save();ctx.font=`900 ${size}px "Font Awesome 6 Free"`;ctx.textAlign='center';ctx.textBaseline='bottom';ctx.lineJoin='round';ctx.strokeStyle='#17131F';ctx.lineWidth=Math.max(2,Math.min(3,size*.12));ctx.strokeText('\uf3c5',x,y+2);ctx.fillStyle=color;ctx.fillText('\uf3c5',x,y+2);ctx.restore()}
function draw(){resize();ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.fillStyle='#E7F3EE';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.lineCap='round';ctx.lineJoin='round';const scale=fitScale()*view.zoom;const roadScale=canvas.clientWidth<=620?.55:canvas.clientWidth<=980?.78:1;
data.lines.forEach(line=>{const pts=line.pts;if(pts.length<4)return;ctx.beginPath();for(let i=0;i<pts.length;i+=2){const p=toScreen(pts[i],pts[i+1]);if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.strokeStyle=line.kind==='round'?'#F1C65A':'#FFFFFF';ctx.lineWidth=Math.max(.75,(line.kind==='round'?4.5:2.8)*view.zoom*roadScale);ctx.stroke();if(line.kind==='walk'){ctx.strokeStyle='rgba(23,19,31,.14)';ctx.lineWidth=Math.max(.45,.8*view.zoom*roadScale);ctx.stroke()}});
screenShapes=[];const visible=data.places.filter(p=>!p.pin&&p.rings&&p.rings.length&&!hidden.has(p.cat)).sort((a,b)=>project(a.cx,a.cy).y-project(b.cx,b.cy).y);visible.forEach(p=>{const color=colors[p.cat]||'#CEC2FF',raise=flat?0:Math.min(20,Math.max(3,p.h*scale*.7));p.rings.forEach(r=>{const base=pathFromRing(r,0),top=pathFromRing(r,raise);if(!flat){ctx.fillStyle='rgba(23,19,31,.18)';ctx.fill(base);ctx.save();ctx.translate(0,raise*.55);ctx.fillStyle=shade(color,-38);ctx.fill(top);ctx.restore()}ctx.fillStyle=p===selected?'#FFD252':p===hovered?shade(color,20):color;ctx.strokeStyle='#17131F';ctx.lineWidth=p===selected?2.5:Math.max(.75,1.1*view.zoom);ctx.fill(top);ctx.stroke(top);screenShapes.push({place:p,ring:r,raise})})});
if(view.zoom>.7){visible.filter(p=>p.named&&p.area>900).slice(0,42).forEach(p=>{const q=toScreen(p.cx,p.cy);ctx.font=`${Math.max(9,Math.min(13,10*view.zoom))}px Cairo`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=3;ctx.strokeStyle='rgba(255,255,255,.9)';ctx.strokeText(p.name,q.x,q.y-8);ctx.fillStyle='#17131F';ctx.fillText(p.name,q.x,q.y-8)})}
if(routePath.length){const routeScale=canvas.clientWidth<=620?.42:canvas.clientWidth<=980?.65:1;const trace=()=>{ctx.beginPath();routePath.forEach((idx,i)=>{const q=toScreen(nodes[idx].x,nodes[idx].y);if(i)ctx.lineTo(q.x,q.y);else ctx.moveTo(q.x,q.y)})};trace();ctx.strokeStyle='#17131F';ctx.lineWidth=Math.max(3.5,6.5*view.zoom*routeScale);ctx.stroke();trace();ctx.strokeStyle='#FFD252';ctx.lineWidth=Math.max(1.8,3.2*view.zoom*routeScale);ctx.stroke();const markerSize=Math.max(17,Math.min(24,20*view.zoom*(canvas.clientWidth<=620?.88:1)));[routePath[0],routePath[routePath.length-1]].forEach((idx,i)=>{const q=toScreen(nodes[idx].x,nodes[idx].y);drawLocationIcon(q.x,q.y,i?'#F06BD7':'#42D5C7',markerSize)})}
if(selected&&(!routePath.length||selected.ent!==routePath[routePath.length-1])){const q=toScreen(selected.cx,selected.cy);const markerSize=canvas.clientWidth<=620?18:22;drawLocationIcon(q.x,q.y-4,'#F06BD7',markerSize)}}
function resize(){const dpr=Math.min(window.devicePixelRatio||1,2),w=stage.clientWidth,h=stage.clientHeight;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}}
function pointInRing(x,y,ring,raise){let inside=false;const pts=[];for(let i=0;i<ring.length;i+=2){const p=toScreen(ring[i],ring[i+1]);pts.push([p.x,p.y-raise])}for(let i=0,j=pts.length-1;i<pts.length;j=i++){const xi=pts[i][0],yi=pts[i][1],xj=pts[j][0],yj=pts[j][1];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi))inside=!inside}return inside}
function hit(x,y){for(let i=screenShapes.length-1;i>=0;i--)if(pointInRing(x,y,screenShapes[i].ring,screenShapes[i].raise))return screenShapes[i].place;return null}
function showDetails(p){selected=p;details.innerHTML=`<h3>${p.name}</h3><p>${labels[p.cat]||'معلم جامعي'}${p.lv?` • ${p.lv} طوابق`:''}${p.area?` • ${p.area.toLocaleString('ar-JO')} م²`:''}</p><div class="place-actions"><button class="place-action" id="setRouteStart">اجعله نقطة البداية</button><button class="place-action alt" id="setRouteEnd">اجعله الوجهة</button></div><p class="map-source">الموقع والتفاصيل ضمن خريطة الجامعة التفاعلية.</p>`;document.getElementById('setRouteStart').onclick=()=>{routeStart.value=p.id;routeStart.focus()};document.getElementById('setRouteEnd').onclick=()=>{routeEnd.value=p.id;routeEnd.focus()};renderResults(search.value);draw()}
function shortestPath(start,end){const dist=new Float64Array(nodes.length);dist.fill(Infinity);dist[start]=0;const prev=new Int32Array(nodes.length);prev.fill(-1);const heap=[[0,start]];const push=item=>{heap.push(item);let i=heap.length-1;while(i){const p=(i-1)>>1;if(heap[p][0]<=item[0])break;heap[i]=heap[p];i=p}heap[i]=item};const pop=()=>{const root=heap[0],last=heap.pop();if(heap.length){let i=0;while(true){const l=i*2+1,r=l+1;if(l>=heap.length)break;const c=r<heap.length&&heap[r][0]<heap[l][0]?r:l;if(heap[c][0]>=last[0])break;heap[i]=heap[c];i=c}heap[i]=last}return root};while(heap.length){const [d,u]=pop();if(d!==dist[u])continue;if(u===end)break;for(const [v,w] of graph[u]){const nd=d+w;if(nd<dist[v]){dist[v]=nd;prev[v]=u;push([nd,v])}}}if(!Number.isFinite(dist[end]))return null;const path=[];for(let at=end;at!==-1;at=prev[at])path.push(at);path.reverse();return{path,distance:dist[end]}}
function runRoute(){const from=data.places.find(p=>String(p.id)===routeStart.value),to=data.places.find(p=>String(p.id)===routeEnd.value);if(!from||!to){routeResult.className='route-result error';routeResult.textContent='اختَر نقطة البداية والوجهة أولًا.';return}if(from.id===to.id){routeResult.className='route-result error';routeResult.textContent='اختَر موقعين مختلفين.';return}const route=shortestPath(from.ent,to.ent);if(!route){routeResult.className='route-result error';routeResult.textContent='تعذّر إيجاد مسار بين الموقعين.';return}routePath=route.path;routeDistance=route.distance;routeResult.className='route-result ready';routeResult.innerHTML=`<strong>${from.name} ← ${to.name}</strong><span>${Math.round(routeDistance).toLocaleString('ar-JO')} متر • ${Math.max(1,Math.ceil(routeDistance/78)).toLocaleString('ar-JO')} دقيقة مشي تقريبًا</span>`;selected=to;view.zoom=Math.max(view.zoom,1.18);const mid=nodes[routePath[Math.floor(routePath.length/2)]],q=toScreen(mid.x,mid.y);view.panX+=canvas.clientWidth/2-q.x;view.panY+=canvas.clientHeight/2-q.y;showDetails(to)}
function centerOn(p){const q=toScreen(p.cx,p.cy);view.panX+=canvas.clientWidth/2-q.x;view.panY+=canvas.clientHeight/2-q.y;showDetails(p)}
function renderResults(value=''){const term=value.trim();const matches=data.places.filter(p=>p.named&&!hidden.has(p.cat)&&(!term||p.name.includes(term))).sort((a,b)=>b.area-a.area).slice(0,term?25:12);results.innerHTML=matches.length?'':'<div class="map-empty">ما لقينا مكان بهذا الاسم</div>';matches.forEach(p=>{const b=document.createElement('button');b.className='map-result'+(selected===p?' active':'');b.textContent=p.name;b.onclick=()=>centerOn(p);results.appendChild(b)})}
document.getElementById('filters').innerHTML=Object.entries(labels).map(([key,label])=>`<button class="filter-chip" data-cat="${key}">${label}</button>`).join('');document.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>{const cat=b.dataset.cat;if(hidden.has(cat)){hidden.delete(cat);b.classList.remove('off')}else{hidden.add(cat);b.classList.add('off')}renderResults(search.value);draw()});
search.oninput=()=>renderResults(search.value);canvas.addEventListener('wheel',e=>{e.preventDefault();view.zoom=Math.max(.45,Math.min(5,view.zoom*(e.deltaY<0?1.12:.89)));draw()},{passive:false});canvas.onpointerdown=e=>{dragging=true;moved=false;last={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging')};canvas.onpointermove=e=>{if(dragging){const dx=e.clientX-last.x,dy=e.clientY-last.y;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;view.panX+=dx;view.panY+=dy;last={x:e.clientX,y:e.clientY};draw()}else{const r=canvas.getBoundingClientRect();hovered=hit(e.clientX-r.left,e.clientY-r.top);draw()}};canvas.onpointerup=e=>{if(!moved){const r=canvas.getBoundingClientRect(),p=hit(e.clientX-r.left,e.clientY-r.top);if(p)showDetails(p)}dragging=false;canvas.classList.remove('dragging')};
document.getElementById('zoomIn').onclick=()=>{view.zoom=Math.min(5,view.zoom*1.25);draw()};document.getElementById('zoomOut').onclick=()=>{view.zoom=Math.max(.45,view.zoom*.8);draw()};document.getElementById('resetMap').onclick=()=>{view.zoom=1;view.panX=view.panY=0;selected=null;details.innerHTML='<h3>اختَر مكانًا من الخريطة</h3><p>اضغط على أي مبنى أو ابحث عنه بالاسم.</p>';draw()};document.getElementById('modeToggle').onclick=e=>{flat=!flat;e.currentTarget.textContent=flat?'عرض مجسّم':'عرض مسطّح';view.panX=view.panY=0;draw()};
const routePlaces=data.places.filter(p=>p.named&&Number.isInteger(p.ent)&&!hidden.has(p.cat)).sort((a,b)=>a.name.localeCompare(b.name,'ar'));const routeOptions='<option value="">اختَر الموقع</option>'+routePlaces.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');routeStart.innerHTML=routeOptions;routeEnd.innerHTML=routeOptions;document.getElementById('routeGo').onclick=runRoute;document.getElementById('routeSwap').onclick=()=>{const v=routeStart.value;routeStart.value=routeEnd.value;routeEnd.value=v;if(routeStart.value&&routeEnd.value)runRoute()};document.getElementById('routeClear').onclick=()=>{routePath=[];routeDistance=0;routeStart.value=routeEnd.value='';routeResult.className='route-result';routeResult.textContent='اختَر موقعين واضغط «اعرض المسار».';draw()};window.addEventListener('resize',draw);renderResults();draw();if(document.fonts?.ready)document.fonts.ready.then(draw);
})();
