(()=>{
const subjects={english:{icon:'EN',description:'اختبار اللغة الإنجليزية في القواعد والمفردات والاستخدام الصحيح.'},arabic:{icon:'ع',description:'اختبار اللغة العربية في النحو والصرف والأدب والبلاغة.'},computer:{icon:'01',description:'اختبار مهارات الحاسوب والبرامج والمفاهيم الرقمية الأساسية.'}};
const key=new URLSearchParams(location.search).get('subject')||'english',subject=subjects[key]?key:'english',bank=window.VORTEXA_QUIZZES[subject],questions=bank.questions;
const $=id=>document.getElementById(id),welcome=$('quizWelcome'),panel=$('quizPanel'),summary=$('quizSummary'),optionsBox=$('quizOptions'),feedback=$('quizFeedback');let index=0,answers=[],locked=false;
document.title=`${bank.title} | Sanafur HU`;$('quizIcon').textContent=subjects[subject].icon;$('welcomeTitle').textContent=bank.title;$('welcomeText').textContent=subjects[subject].description;$('questionCount').textContent=questions.length.toLocaleString('ar-JO');$('quizSubject').textContent=bank.title;
function showQuestion(){locked=false;feedback.className='quiz-feedback';feedback.textContent='';$('nextQuestion').hidden=true;const q=questions[index];$('quizCounter').textContent=`السؤال ${index+1} من ${questions.length}`;$('questionLabel').textContent=`سؤال ${index+1}`;$('quizQuestion').textContent=q.question;$('quizQuestion').dir=subject==='english'?'ltr':'auto';$('quizProgress').style.width=`${((index+1)/questions.length)*100}%`;$('liveScore').textContent=`${answers.filter(a=>a.correct).length.toLocaleString('ar-JO')} صحيحة`;optionsBox.innerHTML='';q.options.forEach((option,choice)=>{const button=document.createElement('button');button.className='quiz-option';button.type='button';button.dir='auto';button.innerHTML=`<span>${String.fromCharCode(65+choice)}</span><b></b>`;button.querySelector('b').textContent=option;button.onclick=()=>choose(choice);optionsBox.appendChild(button)});window.scrollTo({top:panel.offsetTop-110,behavior:'smooth'})}
function choose(choice){if(locked)return;locked=true;const q=questions[index],correct=choice===q.answer;answers[index]={choice,correct};[...optionsBox.children].forEach((button,i)=>{button.disabled=true;if(i===q.answer)button.classList.add('correct');if(i===choice&&i!==q.answer)button.classList.add('wrong')});feedback.classList.add(correct?'is-correct':'is-wrong');feedback.textContent=correct?'إجابة صحيحة! ممتاز 👏':`إجابة خاطئة. الإجابة الصحيحة: ${q.options[q.answer]}`;$('liveScore').textContent=`${answers.filter(a=>a.correct).length.toLocaleString('ar-JO')} صحيحة`;$('nextQuestion').textContent=index===questions.length-1?'اعرض النتيجة والملخص':'السؤال التالي';$('nextQuestion').hidden=false}
function finish(){panel.hidden=true;summary.hidden=false;const correct=answers.filter(a=>a.correct).length,wrong=questions.length-correct,percent=Math.round(correct/questions.length*100);$('scorePercent').textContent=`${percent}%`;$('scoreFraction').textContent=`${correct.toLocaleString('ar-JO')} من ${questions.length.toLocaleString('ar-JO')}`;$('correctCount').textContent=correct.toLocaleString('ar-JO');$('wrongCount').textContent=wrong.toLocaleString('ar-JO');$('totalCount').textContent=questions.length.toLocaleString('ar-JO');$('summaryTitle').textContent=percent>=85?'نتيجة ممتازة!':percent>=65?'شغل مرتب، كمّل مراجعة':'محاولة جيدة، راجع أخطاءك';$('summaryMessage').textContent=wrong?`أنهيت اختبار ${bank.title}. جهزنا لك بالأسفل كل سؤال أخطأت به مع إجابتك والإجابة الصحيحة.`:`أجبت عن جميع أسئلة ${bank.title} بشكل صحيح. إنجاز رائع!`;$('summaryMark').textContent=wrong?'V':'✓';const list=$('wrongList');list.innerHTML='';questions.forEach((q,i)=>{if(answers[i].correct)return;const card=document.createElement('article');card.className='wrong-card';const heading=document.createElement('h4');heading.textContent=`${i+1}. ${q.question}`;const yours=document.createElement('p');yours.className='your-answer';yours.innerHTML='<span>إجابتك</span>';yours.append(document.createTextNode(q.options[answers[i].choice]));const right=document.createElement('p');right.className='right-answer';right.innerHTML='<span>الإجابة الصحيحة</span>';right.append(document.createTextNode(q.options[q.answer]));card.append(heading,yours,right);list.appendChild(card)});$('wrongReview').hidden=!wrong;window.scrollTo({top:summary.offsetTop-110,behavior:'smooth'})}
$('startQuiz').onclick=()=>{welcome.hidden=true;panel.hidden=false;index=0;answers=[];showQuestion()};$('nextQuestion').onclick=()=>{if(index<questions.length-1){index++;showQuestion()}else finish()};$('retryQuiz').onclick=()=>{summary.hidden=true;panel.hidden=false;index=0;answers=[];showQuestion()};
})();
